### ISSUE TITLE
I'm having an issue accessing collections

### ISSUE THREAD

**Issue by pastorryanhayden** [aryehraber/statamic-fetch#10]
When I enter the name of a collection that doesn't exist I get a "[name] doesn't exist screen" and I can get json from pages.  But when I try to get a collection it's throwing this error:
![screen shot 2018-06-15 at 7 44 05 am](https://user-images.githubusercontent.com/4194905/41468565-08aa5d7a-7070-11e8-80cc-6f134f0769d0.png)

**Comment by pastorryanhayden** [comment]
By the way, what I'm trying to do is build a mapbox map using your location addon.  I really appreciate your work.  This task would be much harder without these two addons.

**Comment by aryehraber** [comment]
@pastorryanhayden I'm not completely certain what you're describing above. Would you be able to supply some more details to allow me to recreate the issue (page/collection/entry config & example data).

Thanks, I'm glad to hear these addons are useful!

**Comment by pastorryanhayden** [comment]
Sorry it’s taken so long to reply.
I’ve got a collection called “Missionaries” that I was planning to cast to JSON using your plugin so I could consume it via a custom Vue map component.
Inside of that collection, I am using the field provided by your location add on to get latitude and longitude by search query.  
The problem could be in either repository, but when I use the fetch tag for that collection containing the data from the location addon, I get the error shown above.  
**It looks like the issue is that it doesn’t turn the float from one of the latitude and longitude values into a string and statamic doesn’t know what to do with that.**

**Comment by aryehraber** [comment]
Just read your corresponding issue (https://github.com/aryehraber/statamic-location/issues/3#issue-336190468).

Can you confirm it works if you manually add quotes `""` around the positive Lat/Long values.

**Comment by pastorryanhayden** [comment]
Yes it works, but I also noticed that whether or not it is saved as a string is random.  Sometimes it is, sometimes it isn’t on both negative and positive numbers.

**Comment by aryehraber** [comment]
Alright, this should be enough info for more focused debugging on my end. Will hopefully be able to carve our some time for this in July.

Thanks for the help!

**Comment by aryehraber** [comment]
This issue has finally been fixed in v4.1.1. 

Apologies for the delay!

**Comment by jdsimcoe** [comment]
@aryehraber I'm not using the fetch plugin but I am using `statamic-location` and I have a similar problem of random negative `long` values being saved as strings which Mapbox is getting borked on: https://github.com/aryehraber/statamic-location/issues/3. Any ideas how to fix this in the location plugin?
