### ISSUE TITLE
Call to Fetch also fetches the drafts

### ISSUE THREAD

**Issue by 1stevengrant** [aryehraber/statamic-fetch#15]
I would have expected Fetch to only grab entries that have actually been published.

**Comment by aryehraber** [comment]
Fetch currently doesn't support any kind of filtering of data, including unpublished. This feature has been on the roadmap for some time, but due to time limitations, never came to fruition. 

If you're willing/able to help, I'd be more than happy to accept a PR!

**Comment by aryehraber** [comment]
It must be your lucky day... After all this time, I actually needed this feature myself today!

Running some final tests on the changes atm, and should be released later today.

**Comment by aryehraber** [comment]
This feature has now been released 🎉 

It should make its way to Statamic's Marketplace soon, but for now you can download the release directly using: https://github.com/aryehraber/statamic-fetch/releases/tag/v3.4

The docs have also been [updated](https://github.com/aryehraber/statamic-fetch/blob/master/DOCUMENTATION.md#options). 

Feel free to re-open if you come across any issues!

**Comment by 1stevengrant** [comment]
What a champ! Done before I even had time to chime back in. I'd love to get to building new and enhancing existing Statamic addons.

**Comment by 1stevengrant** [comment]
And thank you 🎉

**Comment by aryehraber** [comment]
No problem at all! 

I have some big plans for the next major release, and hope to rebuild it in a much cleaner & more modular way to make it easier to add new features. Just need to find the time...

If you have any further suggestions, feel free to open up new issues and/or PRs 😄
