### ISSUE TITLE
Request an individual entry

### ISSUE THREAD

**Issue by markzegarelli** [aryehraber/statamic-fetch#19]
I saw that there was a closed ticket that relates to this, but is there way to access an individual entry? Either by ID as a parameter, or by URL (via routing)?

**Comment by aryehraber** [comment]
Hi @markzegarelli, thanks for opening this issue. 

This feature isn't supported yet actually, but totally should. I'll see if I can whip something some time this week (no promises), but it shouldn't be too hard to add.
