### ISSUE TITLE
FR: Nested pages

### ISSUE THREAD

**Issue by rrelmy** [aryehraber/statamic-fetch#25]
In many occasions it would be useful to be able to get the page tree instead of a flat list of pages.

[Content::tree](https://docs.statamic.com/addons/api/api-content#get-the-content-structure-tree) is able to generate a tree of pages with a specific depth.

## Proposed changes
Changes apply to the `/pages` and `/page` endpoint.

- New parameter `nested` (Default: `false` for backwards compatibility)
- New parameter `depth` (Default: `null` unlimited)

### `/pages`
If `nested` is `true` the list of pages is no longer a flat list.
If `pages` is set, those pages are on the top level and contain their children if `nested` is set

---

Any objections on this?
I would implement it myself

**Comment by aryehraber** [comment]
This sounds great, thanks @rrelmy! Will gladly look over a PR once ready.

**Comment by aryehraber** [comment]
@rrelmy Just a heads up, I merged a PR just now that makes some internal changes to how `$data` is passed around inside of `Fetch.php` -- might want to pull latest or rebase if you've already started work on this.
