### ISSUE TITLE
unexpected 'global' error

### ISSUE THREAD

**Issue by craigb88** [aryehraber/statamic-fetch#28]
I seem to be getting the following error. 

FatalErrorException in Fetch.php line 146:
syntax error, unexpected 'global' (T_GLOBAL), expecting identifier (T_STRING)
1. in Fetch.php line 146

My ajax call is below 

        ```
         $.ajax({
            type: 'GET',
            url: "/!/Fetch/entry/team/",
            dataType: 'json',
            success: function (data) {
                console.log(data);
            },
            error: function(error) {
                console.log(error);
            }

        }); 
```

**Comment by aryehraber** [comment]
This might be caused by the PHP version, Fetch requires PHP 7 and up. I don’t think that’s mentioned in the docs, so will make a point to add it! Could that be the case for you?

**Comment by craigb88** [comment]
> This might be caused by the PHP version, Fetch requires PHP 7 and up. I don’t think that’s mentioned in the docs, so will make a point to add it! Could that be the case for you?

I meant to come update this yesterday. I was using an old version of php updating fixed it like you said. 
Thanks
