### ISSUE TITLE
Not showing in CP addon

### ISSUE THREAD

**Issue by monstromatic** [aryehraber/statamic-fetch#38]
Hello,

I'm using statamic 2.11.3 and the Fetch addon doesn't show up in the addon CP... I drop the Fetch folder in the addon folder as my another addons and nothing append. Even if I refresh and restart server and clear cache. When I do a query with Axios, no error but a 204 No content response on every type of data (page, globals, etc.)

**Comment by aryehraber** [comment]
Are you sure you copied the correct folder into `/addons`? When downloading the addon, you don't copy the entire contents of the zip, just the inner `Fetch` folder.

**Comment by monstromatic** [comment]
Yes, absolutely :-)

**Comment by aryehraber** [comment]
Hmm, very odd! The addon doesn't have any dependencies, so it should _Just Work™_...

Does anything show when you visit `/!/Fetch/collection/[collection_handle_here]` in your browser? Any errors in your log file?

**Comment by monstromatic** [comment]
My bad, I copy the folder in 'site/settings' instead of 'site'... so sorry about that. You can close the issue.

**Comment by aryehraber** [comment]
Haha, ok no problem 😊
