### ISSUE TITLE
500 when attempting to fetch an entry

### ISSUE THREAD

**Issue by andyra** [aryehraber/statamic-fetch#45]
I'm attempting to fetch an entry from its ID like so:

```{{ fetch entry="bbb21f23-48ae-499c-929d-a2cf933c4d39" }}```

and I'm getting this error:

```
FatalThrowableError in FetchTags.php line 45:
Method name must be a string
```

Using the **/collection/entry-slug** syntax yields the same results. I _am_ able to successfully get a collection, however, via `{{ fetch collection="songs" }}`.

Any idea why collections would be working, but not entries?

**Comment by aryehraber** [comment]
Hmm, your example tag works on my end (changing the ID of course).

Can you confirm that you're on the latest version of Fetch & Statamic?

**Comment by andyra** [comment]
Ah, I downloaded Fetch from the [v3 docs](https://statamic.com/marketplace/addons/fetch/v3/docs)—good call. I'll try the newest version later tonight—thanks!
