### ISSUE TITLE
Sorting Data

### ISSUE THREAD

**Issue by yawuar** [aryehraber/statamic-fetch#55]
Hi!

Just a small question but I'm trying to figure out how to sort my data?
I tried using `sort=publish_date:desc` in axios but that doesn't work.

In PHP it works, this is my code
```
{{ collection:cases limit="15" sort="publish_date:desc" }}
                <a class="col-sm-6 col-md-4 grid-item {{ if index % 2 == 0 }} grid-item--height2 {{ /if }}" href="{{ permalink }}">
                    <img src="{{ hero_image }}" />
                    <span class="overlay">
                        <span class="inner">
                            <p class="title">{{ sub_title }}</p>
                            <p class="sub_title">{{ title }}</p>
                            <span href="{{ permalink }}" class="detail">+ view project</span>
                        </span>
                    </span>
                </a>
{{ /collection:cases }}
```
But in JS it doesn't work
```
axios.get('/!/Fetch/collection/cases?sort=publish_date:desc').then(
function(cases) {
    }
);
```

Do you guys know how to sort the data?

Thanks

Yawuar

**Comment by aryehraber** [comment]
Hi @yawuar, I'm afraid sorting isn't supported at this moment. I'm not sure where you got this syntax from `?sort=publish_date:desc`, or perhaps it was just wishful thinking.

You'll have to do the sorting on the JS-side, here's a tweaked working example:

```js
axios.get('/!/Fetch/collection/cases').then(resp => {
  const sortedData = resp.data.data.sort((a, b) => a.order > b.order)

  console.log(sortedData)
});
```

Tweak as needed using the `sort` docs: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by yawuar** [comment]
Yeah it was wishful thinking :p
Thanks anyways!
