### ISSUE TITLE
Retrieve image asset focal points?

### ISSUE THREAD

**Issue by jarred** [aryehraber/statamic-fetch#62]
Thank you for creating this plugin! It has made using Statamic as a headless CMS relatively easy.

Is it possible to access the focal points of images in the JSON output?

something like

```json
{
  "hero_image": "http://website.com/assets/img/frame-hero.jpg",
  "hero_image_focal_points": {
    "x": "50%",
    "y": "74%"
  }
}
```

Including the `title` and `alt text` associated with an image asset would be great too.

Perhaps they should be nested? And triggered with a parameter as to not break existing implementations?

eg `/!/Fetch/collection/project?asset_deep=true`

```json
{
  "hero_image": {
    "src": "http://website.com/assets/img/frame-hero.jpg",
    "focal_point_x": "50%",
    "focal_point_y": "74%",
    "title": "Image title text...",
    "alt": "Image alt text..."
  }
}
```

I see #57 & #58 but am not sure how to access this data

**Comment by aryehraber** [comment]
Hi @jarred! There's an Assets endpoint that you can use (just noticed it's undocumented) which should return all the asset details you need (alt text, focal point, and more).

To fetch all assets you can use `/!/Fetch/assets` (accepts an optional `container` query param), or to fetch a specific asset you can use `/!/Fetch/asset` passing an `id` query param, like so: `/!/Fetch/asset?id=main::img/banner.jpg` (note the `id` contains the asset's container as a prefix).

There isn't a great way to combine this with the Collection endpoint at the moment, but hopefully you'll be able to make something work.

Good luck!

**Comment by jarred** [comment]
Thanks @aryehraber! I can make do with this.
