### ISSUE TITLE
json Forms

### ISSUE THREAD

**Issue by stillzombie** [aryehraber/statamic-fetch#63]
I dont know if this add-on can handle forms or not, i tried on page with a form and it seems it ignores completely the form, or maybe i just dont know how to do it, any advice on how to achieve this or is any plan for pr for this feature ?

**Comment by aryehraber** [comment]
Hi @stillzombie! 

Form handling over ajax is actually possible in Statamic out-of-the-box 😊 

I'm not sure if it's properly documented but you essentially POST to `/!/Form/create` with a few additional hidden (& encypted) params that Statamic requires to figure out which Formset the submission is meant for, etc. Getting the encryped params from Statamic is the tough part if you're using Statamic in a headless CMS setup. 

Hope to add a `Formset` endpoint some time soon to make this a bit easier, and release it together with an example in the Fetch docs. Will mark this issue as a FR until then!

**Comment by stillzombie** [comment]
Thanks having a Formset endpoint will be great, if need any help with a pr. i will glad to help

**Comment by aryehraber** [comment]
Thanks for the PR offer! I actually have some code laying around _somewhere_ since I needed this for a project a while ago but never officially pushed it to Fetch (you're the first dev to ask for this feature 😉). I'll try and get it up for you asap!

**Comment by aryehraber** [comment]
Just pushed a new release (v4.9) that adds support for fetching Formsets! 

Also updated the [docs with an example](https://github.com/aryehraber/statamic-fetch/blob/master/DOCUMENTATION.md#formset-examples), feel free to comment here or open a new issue if anything is unclear or doesn't work.

**Comment by stillzombie** [comment]
Fantastic, thanks a lot

**Comment by stillzombie** [comment]
Works perfectly.
What would you recommend to do, if i have a contact page and i want to fetch all the data in json from there, including the form attached to this page, how would you handle this situations for example?

**Comment by aryehraber** [comment]
Assuming with "fetch all the data in json" you mean fetch the formset's fields, you could do something like:

```js
axios.get('/!/Fetch/formset/contact').then(resp => {
    const fields = resp.data.data.fields

    // update form by iterating over fields object
});
```

If you're using something like Vue or React, you could make `fields` a reactive property which you can then setup to automatically populate the form in your template.

I guess you've already seen this from testing, but here's an example of the output from my test contact formset:

```
{
    "data": {
        "title": "Contact",
        "fields": {
            "name": {
                "display": "Name",
                "validate": "required|min:2"
            },
            "email": {
                "display": "Email",
                "validate": "required|email"
            },
            "message": {
                "display": "Message"
            }
        },
        "params": "eyJpdiI6IkJzZ1NqNFVzR1JVUzVTQ1N1amhJc2c9PSIsInZhbHVlIjoiSTg4TUJrbHRqWGQwZUZwZUFBNHdmZnJoT2JvTDl5aVNkY2JqRmFwdlhlMm5ZelBGNXlmSXE2ZklLUWVyUWlvciIsIm1hYyI6IjQzMGIxNWYzNzRhNDMwMTljYzFjODVlNzQyYTkxNjA2M2Q5NDdhNzdiNWVhYjhiMTI2N2JiMWQyOTFlMWQzMjQifQ=="
    }
}
```

Notice the `validate` keys which you can use to perform some front-end validation if you'd like.
