### ISSUE TITLE
Stache cleared on every request

### ISSUE THREAD

**Issue by wanze** [aryehraber/statamic-fetch#66]
This was a tough one to find 😅 

### Problem

The addon modifies Statamic's config at runtime in `FetchServiceProvider::boot` by adding `/!/Fetch*` to `system.csrf_exclude`. On each request, Statamic also checks if the stache should be cleared due to config changes. Statamic checks if the config in the stache is equal with the config on the filesystem. If not, the stache is cleared. This check is performed in the "boot" process in `StacheServiceProvider::clearOnConfigChange`. Now:  If the stache service provider performs its check after Fetch modifies the config, the Stache is cleared on every request, because the config is never identical.

I'm not sure if this is always the case, but it happens if `StacheServiceProvider::boot` is called after `FetchServiceProvider::boot` in the bootstrapping process.

### Solution

It would probably be better to avoid config changes at runtime and let the user explicitly add the route to `system.csrf_exclude` manually. If one uses Fetch with GET requests only, this step is not necessary, as no CSRF tokens are involved.

Cheers

**Comment by aryehraber** [comment]
Hi @wanze, thank you very much for bringing this to my attention! 

I'm curious though, wouldn't the check on boot work as expected after the first request has taken place (where `system.csrf_exclude` has been modified)? After Fetch adds the `/!/Fetch` route once, the system config shouldn't be getting changed again.

It sounds like you've been doing some digging here, what's the best way for me to recreate this locally so I can do some testing on my end? Just using the method you pointed out?

```php
// StacheServiceProvider

private function clearOnConfigChange()
{
    if ($this->manager->hasConfigChanged()) {
        // Log here?

        \Statamic\API\Stache::clear();
    }
}
```

If it turns out that the Stache is getting cleared on _every request_ because of Fetch then you are totally right and a manual step will be added to the docs. This was added to make things as easy as possible for users, just drop in and go, but if it comes at a performance cost then it isn't worth it!

Thanks again!

**Comment by wanze** [comment]
Hi @aryehraber 

> I'm curious though, wouldn't the check on boot work as expected after the first request has taken place (where system.csrf_exclude has been modified)? After Fetch adds the /!/Fetch route once, the system config shouldn't be getting changed again.

I think the configuration is only modified at runtime but not persisted. So the problem happens again in the next request. Just checked the `Statamic\API\Config` facade and it seems that you need to call `Config::save` to persist config changes on the file system. Fetch only uses `Config::set`. Maybe this was changed in Statamic?

> It sounds like you've been doing some digging here, what's the best way for me to recreate this locally so I can do some testing on my end? Just using the method you pointed out?

You can reproduce it like this:

1. Remove `/!/Fetch*` from `system.csrf_exclude`
2. Debug `Statamic\Stache\Manager::hasConfigChanged`. In my case, this method is always returning `true`.

I was using xdebug to compare the two arrays compared in `Statamic\Stache\Manager::hasConfigChanged`. The only difference was the Fetch route in `system.csrf_exclude`.

Hope this helps to reproduce the issue :) Let me know if you need more information.

Cheers

**Comment by aryehraber** [comment]
Thanks for another detailed answer @wanze, sounds like this might be the reason:

> Just checked the Statamic\API\Config facade and it seems that you need to call Config::save to persist config changes on the file system.

I've just pushed a branch with the fix, would you mind testing before I release this? No rush, whenever you have time!

Direct download: https://github.com/aryehraber/statamic-fetch/archive/fix/save-config.zip

**Comment by wanze** [comment]
I just tested your fix locally and it works as expected, the url is now also saved in the config file.  🎉 
Guess this can be closed then - thanks! :) 

Cheers

**Comment by aryehraber** [comment]
Perfect, thanks for testing (and pretty much debugging this whole issue) @wanze, very much appreciated! Will officially release the fix later today 🎉
