### ISSUE TITLE
TokenMismatchException with formset

### ISSUE THREAD

**Issue by ryangittings** [aryehraber/statamic-fetch#69]
Hey, 

I get `{"exception":"TokenMismatchException","redirect":"mydomain.com\/cp\/auth\/login?expired=1"}` when submitting to `/!/Form/create` as per your docs (probably me doing something wrong).

Any reason why this would be? I'm successfully getting the params from the `/!/Fetch/formset/contact`, and submitting that. Any help would be much appreciated!

**Comment by ryangittings** [comment]
Ah, I've disabled csrf for that route, and now works. Is that the best solution here?

**Comment by aryehraber** [comment]
Hi @ryangittings! Yes, disabling CSFR tokens for that route is correct. 

The `/!/Form/create` route is a core Statamic feature, all that `/!/Fetch/formset/contact` does is return the formset params needed by Statamic to save submissions to the correct formset, Fetch doesn't actually touch form submissions in any way.
