### ISSUE TITLE
JSON to HTML

### ISSUE THREAD

**Issue by cgrisar** [aryehraber/statamic-fetch#70]
Hi,

I'm using Fetch with Axios in vuejs.

Instead of returning JSON, I'd like to show the result of a collection in HTML-format, using one of the templates I created. How can I achieve that?

Charles

**Comment by aryehraber** [comment]
Hi @cgrisar, I'm afraid Fetch strictly enables your Statamic site to become a JSON API, it isn't meant for your use case.

Having said that, you may be able to build something out yourself using core Statamic by exposing a few endpoints (via `routes.yaml`) which point to some minimal templates (with some params, if needed) that simply return HTML, and then calling those endpoints via Axios.

**Comment by cgrisar** [comment]
Yes, indeed.

That’s what I eventually came up with:
Create a template and work my way through with wildcards in the url to narrow down the selection of a collection using filters

Thanks 

Charles Grisar
