### ISSUE TITLE
Addon causes stache to be cleared on multi-locale site if csrf exclude is not configured

### ISSUE THREAD

**Issue by rrelmy** [aryehraber/statamic-fetch#72]
The `Config::set` in the service provider can cause the stache to be cleared

*Precondition*
- Multiple locales configured
- Only main locale path is in the csrf exclude settings (`/!/Fetch/*`)

*Steps to reproduce*
- Request a page on the main locale
- Request a page on the secondary locale

The stache will be cleared (check `StacheServiceProvider::clearOnConfigChange`) on every request if the locale to the last request changed.
I think setting the exclude temporarily lets the config change each request.

*Fix*
- Save all the excludes to the config manually.

**Comment by rrelmy** [comment]
I just realised this is a duplicate of #66 and the issue has been fixed in a version I did not yet install 🤦

**Comment by aryehraber** [comment]
Hey @rrelmy, been a while, hope all is well! Glad you were able to solve by simply updating to latest version 👍
