### ISSUE TITLE
how do i install on statamic 4?

### ISSUE THREAD

**Issue by jajouka79** [aryehraber/statamic-fetch#74]
the directory site/addons/ doesn't exist

`composer require aryehraber/fetch` 

this doesn't work, 

> Could not find a matching version of package aryehraber/fetch.

**Comment by aryehraber** [comment]
Hi @jajouka79, this addon was built for Statamic 2 only. It was never updated because since Statamic 3 they support API features out-of-the-box: https://statamic.dev/rest-api

**Comment by jajouka79** [comment]
thanks very much!

**Comment by jajouka79** [comment]
i was looking at fetch because i couldn't work out how to retirve a page by slug or page title through the statamic 4 rest api. it seems that you need to know the uid of the page

**Comment by aryehraber** [comment]
Oh ok, that's a shame — I'm not familiar with Statamic's Rest API feature tbh (doing mostly Laravel dev these days). 

Perhaps you'd have better luck asking in Statamic's Discord server. Good luck!
